const QUESTIONS = [
  // ===== E/I Dimension (1-18) =====
  { id:1,dim:'EI',dir:1,zh:'我享受参加社交活动，结识新朋友',en:'I enjoy attending social events and meeting new people' },
  { id:2,dim:'EI',dir:-1,zh:'独处时我感觉精力最充沛',en:'I feel most energized when I am alone' },
  { id:3,dim:'EI',dir:1,zh:'我更喜欢在团队中工作而不是独自工作',en:'I prefer working in a team rather than alone' },
  { id:4,dim:'EI',dir:-1,zh:'大型社交聚会很快让我感到疲惫',en:'Large social gatherings quickly drain my energy' },
  { id:5,dim:'EI',dir:1,zh:'我喜欢成为众人关注的焦点',en:'I enjoy being the center of attention' },
  { id:6,dim:'EI',dir:-1,zh:'说话之前我会先深思熟虑',en:'I think carefully before speaking' },
  { id:7,dim:'EI',dir:1,zh:'我交友广泛，社交圈子很大',en:'I have a wide circle of friends and connections' },
  { id:8,dim:'EI',dir:-1,zh:'我更享受安静的个人时间而非热闹的聚会',en:'I prefer quiet personal time over lively parties' },
  { id:9,dim:'EI',dir:1,zh:'我乐于主动与陌生人展开交谈',en:'I readily strike up conversations with strangers' },
  { id:10,dim:'EI',dir:-1,zh:'闲聊让我感到无聊且消耗精力',en:'Small talk feels boring and draining to me' },
  { id:11,dim:'EI',dir:1,zh:'我通过与别人讨论来理清自己的思路',en:'I clarify my thoughts by discussing them with others' },
  { id:12,dim:'EI',dir:-1,zh:'与社交相比，独处让我感到更加充实',en:'Being alone feels more fulfilling than socializing' },
  { id:13,dim:'EI',dir:-1,zh:'相比大群体，我更喜欢小范围深入交流',en:'I prefer deep conversations in small groups over large ones' },
  { id:14,dim:'EI',dir:1,zh:'在派对上我会主动去认识在场的每个人',en:'At parties, I actively try to meet everyone present' },
  { id:15,dim:'EI',dir:-1,zh:'在社交场合我倾向于安静观察而非积极参与',en:'I tend to observe quietly rather than actively participate in social settings' },
  { id:16,dim:'EI',dir:1,zh:'快节奏、活跃的社交环境让我充满活力',en:'Fast-paced, lively social environments energize me' },
  { id:17,dim:'EI',dir:-1,zh:'周末我更喜欢一个人读书或做自己的事',en:'I prefer spending weekends reading or doing my own things alone' },
  { id:18,dim:'EI',dir:1,zh:'与人互动交流能给我带来很多能量',en:'Interacting with people gives me a lot of energy' },

  // ===== S/N Dimension (19-36) =====
  { id:19,dim:'SN',dir:1,zh:'我更加关注具体细节而非抽象概念',en:'I focus more on concrete details than abstract concepts' },
  { id:20,dim:'SN',dir:-1,zh:'我经常陷入对未来的幻想和想象之中',en:'I often get lost in fantasies and imagination about the future' },
  { id:21,dim:'SN',dir:1,zh:'我习惯根据事实和亲身经验做决定',en:'I base my decisions on facts and personal experience' },
  { id:22,dim:'SN',dir:-1,zh:'我善于发现事物之间隐藏的联系和模式',en:'I am good at noticing hidden connections and patterns between things' },
  { id:23,dim:'SN',dir:1,zh:'我相信眼见为实，注重实际',en:'I believe in what I can see and experience practically' },
  { id:24,dim:'SN',dir:-1,zh:'我享受思考抽象的理论性问题',en:'I enjoy thinking about abstract theoretical questions' },
  { id:25,dim:'SN',dir:1,zh:'我更喜欢简单直接、清晰明了的表达方式',en:'I prefer simple, direct, and clear ways of expression' },
  { id:26,dim:'SN',dir:-1,zh:'我经常使用比喻和象征来理解事物',en:'I often use metaphors and symbols to understand things' },
  { id:27,dim:'SN',dir:1,zh:'我更关注"现在正在发生什么"而非"可能会怎样"',en:'I focus more on \"what is happening now\" than \"what could be\"' },
  { id:28,dim:'SN',dir:-1,zh:'我喜欢探讨各种可能性和潜在的机会',en:'I enjoy exploring various possibilities and potential opportunities' },
  { id:29,dim:'SN',dir:1,zh:'我做事按部就班，注重流程和步骤',en:'I do things step by step, valuing procedures and processes' },
  { id:30,dim:'SN',dir:-1,zh:'我更喜欢创新和打破常规的思维方式',en:'I prefer innovative thinking that breaks the rules' },
  { id:31,dim:'SN',dir:1,zh:'我对周围环境的细节变化很敏锐',en:'I am sensitive to detailed changes in my surroundings' },
  { id:32,dim:'SN',dir:-1,zh:'我更喜欢考虑全局和整体画面而非细节',en:'I prefer considering the big picture rather than details' },
  { id:33,dim:'SN',dir:1,zh:'我倾向于相信自己的亲身经历和直接经验',en:'I tend to trust my personal experiences and direct evidence' },
  { id:34,dim:'SN',dir:-1,zh:'我经常凭直觉就能判断一件事的对错',en:'I can often judge right from wrong by intuition' },
  { id:35,dim:'SN',dir:1,zh:'我做决定时非常依赖事实和数据',en:'I rely heavily on facts and data when making decisions' },
  { id:36,dim:'SN',dir:-1,zh:'我更喜欢天马行空的创意活动',en:'I prefer imaginative and creative activities' },

  // ===== T/F Dimension (37-54) =====
  { id:37,dim:'TF',dir:1,zh:'我做决定时更依赖理性分析而非情感感受',en:'I rely more on rational analysis than emotional feelings when deciding' },
  { id:38,dim:'TF',dir:-1,zh:'我很容易被他人的情绪和感受影响',en:'I am easily affected by others\' emotions and feelings' },
  { id:39,dim:'TF',dir:1,zh:'即使会伤害对方感受，我也会说出真相',en:'I will tell the truth even if it hurts someone\'s feelings' },
  { id:40,dim:'TF',dir:-1,zh:'维护人际关系的和谐对我来说非常重要',en:'Maintaining harmonious relationships is very important to me' },
  { id:41,dim:'TF',dir:1,zh:'评判事物时我更看重逻辑是否成立',en:'I value logical validity more than anything when judging things' },
  { id:42,dim:'TF',dir:-1,zh:'我倾向于同情和支持需要帮助的人',en:'I tend to sympathize with and support those in need' },
  { id:43,dim:'TF',dir:1,zh:'做决策时我更在意公平公正而非个人感受',en:'I care more about fairness and justice than personal feelings' },
  { id:44,dim:'TF',dir:-1,zh:'我常常设身处地地为他人着想',en:'I often put myself in others\' shoes' },
  { id:45,dim:'TF',dir:1,zh:'相比感性交流，我更喜欢理性的辩论',en:'I prefer rational debate over emotional conversations' },
  { id:46,dim:'TF',dir:-1,zh:'我认为感受和情绪应该是决策的重要因素',en:'I believe feelings and emotions should be important factors in decisions' },
  { id:47,dim:'TF',dir:1,zh:'批评别人时我会直接指出问题，不太在意措辞',en:'I point out problems directly when criticizing, without worrying about wording' },
  { id:48,dim:'TF',dir:-1,zh:'我很在意别人对我的看法和评价',en:'I care about what others think of me' },
  { id:49,dim:'TF',dir:1,zh:'我认为逻辑一致性比个人价值观更重要',en:'I think logical consistency is more important than personal values' },
  { id:50,dim:'TF',dir:-1,zh:'我经常为了顾及他人而牺牲自己的需求',en:'I often sacrifice my own needs for the sake of others' },
  { id:51,dim:'TF',dir:1,zh:'我欣赏客观公正、不带偏见的分析',en:'I appreciate objective, unbiased analysis' },
  { id:52,dim:'TF',dir:-1,zh:'做决定时我会考虑对人际关系的长期影响',en:'I consider the long-term impact on relationships when deciding' },
  { id:53,dim:'TF',dir:1,zh:'我更关注一件事"对不对"而非"好不好"',en:'I focus more on whether something is \"right\" than \"nice\"' },
  { id:54,dim:'TF',dir:-1,zh:'我能深切感受到他人的痛苦和快乐',en:'I deeply feel others\' pain and joy' },

  // ===== J/P Dimension (55-72) =====
  { id:55,dim:'JP',dir:1,zh:'我喜欢提前制定详细的计划',en:'I like to make detailed plans in advance' },
  { id:56,dim:'JP',dir:-1,zh:'我更喜欢随遇而安、灵活应对',en:'I prefer to go with the flow and adapt flexibly' },
  { id:57,dim:'JP',dir:1,zh:'我喜欢任务有明确的截止日期',en:'I like tasks to have clear deadlines' },
  { id:58,dim:'JP',dir:-1,zh:'我经常在最后一刻临时改变计划',en:'I often change plans at the last minute' },
  { id:59,dim:'JP',dir:1,zh:'我喜欢整齐有序、条理清晰的生活环境',en:'I like a neat, organized living environment' },
  { id:60,dim:'JP',dir:-1,zh:'我更喜欢自由开放、不受约束的工作方式',en:'I prefer a free, open, and unconstrained work style' },
  { id:61,dim:'JP',dir:1,zh:'我会制定待办清单并按步骤逐一完成',en:'I make to-do lists and complete them step by step' },
  { id:62,dim:'JP',dir:-1,zh:'我在临近截止日期时反而更有灵感和动力',en:'I feel more inspired and motivated closer to deadlines' },
  { id:63,dim:'JP',dir:1,zh:'出门旅行前我会仔细规划好每天的行程',en:'I carefully plan every day\'s itinerary before a trip' },
  { id:64,dim:'JP',dir:-1,zh:'我享受探索新可能性的过程，不急于做决定',en:'I enjoy exploring new possibilities without rushing to decide' },
  { id:65,dim:'JP',dir:1,zh:'我讨厌迟到，凡事都喜欢提前到达',en:'I hate being late and prefer to arrive early for everything' },
  { id:66,dim:'JP',dir:-1,zh:'我经常同时开始多个项目，然后看哪个有进展',en:'I often start multiple projects at once and see which progresses' },
  { id:67,dim:'JP',dir:1,zh:'做事有始有终让我很有成就感',en:'Finishing what I start gives me a great sense of accomplishment' },
  { id:68,dim:'JP',dir:-1,zh:'我的工作空间通常比较随意和杂乱',en:'My workspace is usually casual and messy' },
  { id:69,dim:'JP',dir:1,zh:'我更喜欢稳定和可预测的生活方式',en:'I prefer a stable and predictable lifestyle' },
  { id:70,dim:'JP',dir:-1,zh:'我享受生活中的即兴发挥和意外惊喜',en:'I enjoy improvisation and surprises in life' },
  { id:71,dim:'JP',dir:1,zh:'我习惯每天制定待办事项并按计划执行',en:'I habitually make daily to-do lists and follow them' },
  { id:72,dim:'JP',dir:-1,zh:'我通常凭一时冲动和直觉做决定',en:'I usually make decisions based on impulse and intuition' },
];